# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: translations_sync 0.4.14 ruby lib

Gem::Specification.new do |s|
  s.name = "translations_sync".freeze
  s.version = "0.4.14"

  s.required_rubygems_version = Gem::Requirement.new(">= 0".freeze) if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib".freeze]
  s.authors = ["Dmitri Koulikoff".freeze]
  s.date = "2019-05-23"
  s.description = "Synchronizes the different locales represeinted in yaml for I18n".freeze
  s.email = "koulikoff@gmail.com".freeze
  s.extra_rdoc_files = [
    "README"
  ]
  s.files = [
    "Changelog",
    "MIT-LICENSE",
    "README",
    "Rakefile",
    "init.rb",
    "lib/tasks/translations_sync.rake",
    "lib/translations_sync.rb",
    "spec/spec_helper.rb",
    "translations_sync.gemspec"
  ]
  s.homepage = "http://github.com/dima4p/translations_sync/".freeze
  s.licenses = ["MIT".freeze]
  s.rubygems_version = "3.0.3".freeze
  s.summary = "Synchronizes the different locales represeinted in yaml for I18n".freeze

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<activesupport>.freeze, [">= 0"])
      s.add_runtime_dependency(%q<ya2yaml>.freeze, [">= 0"])
      s.add_development_dependency(%q<jeweler>.freeze, ["~> 2.0"])
    else
      s.add_dependency(%q<activesupport>.freeze, [">= 0"])
      s.add_dependency(%q<ya2yaml>.freeze, [">= 0"])
      s.add_dependency(%q<jeweler>.freeze, ["~> 2.0"])
    end
  else
    s.add_dependency(%q<activesupport>.freeze, [">= 0"])
    s.add_dependency(%q<ya2yaml>.freeze, [">= 0"])
    s.add_dependency(%q<jeweler>.freeze, ["~> 2.0"])
  end
end

